name: test_a11y

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
  test_a11y:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - run: npm ci

      - run: npm run test:a11y
